# Generated by Django 2.2.4 on 2019-09-02 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome completo do aluno, Ex.: 'Carlos Pesenha'", max_length=45)),
                ('email', models.CharField(help_text='endereço de e-mail do aluno, Ex.: email@gmail.com', max_length=45)),
                ('telefone', models.CharField(help_text='telefone do aluno, Ex.: (45)9999-99999', max_length=15)),
            ],
            options={
                'db_table': 'cadastroAluno_aluno',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do curso, Ex.: Ciência da Computação', max_length=45)),
            ],
            options={
                'db_table': 'cadastroAluno_curso',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da disciplina, Ex.: Fisica', max_length=45)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastroAluno.Curso')),
            ],
            options={
                'db_table': 'cadastroAluno_disciplina',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastroAluno.Aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastroAluno.Disciplina')),
            ],
            options={
                'db_table': 'cadastroAluno_matricula',
            },
        ),
    ]
