# Generated by Django 2.2.4 on 2019-09-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroAluno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='curso',
            new_name='cursoDaMateria',
        ),
    ]
