# Generated by Django 2.2.4 on 2019-09-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroAluno', '0002_auto_20190902_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='cursoDaMateria',
            new_name='curso',
        ),
    ]
